# Generated by Django 4.0.8 on 2022-12-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='category_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='example.category'),
        ),
    ]
