# Generated by Django 4.0.8 on 2022-12-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0004_auto_20221213_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['created_date', 'title'], 'verbose_name': 'Бизнесмен', 'verbose_name_plural': 'Бизнесмены'},
        ),
        migrations.AlterField(
            model_name='example',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='aвтоr'),
        ),
        migrations.AlterField(
            model_name='example',
            name='category_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='example.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='example',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dата создание'),
        ),
        migrations.AlterField(
            model_name='example',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='example',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовка'),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example.example', verbose_name='Имя')),
            ],
        ),
    ]
