# Generated by Django 4.0.8 on 2022-12-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_alter_example_options_alter_example_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='name',
            new_name='name_title',
        ),
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
