# Generated by Django 4.0.8 on 2022-12-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_rename_name_links_name_title_alter_example_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='example',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='name_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example.example', to_field='title', verbose_name='Имя'),
        ),
    ]
