# Generated by Django 4.0.8 on 2022-12-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_alter_example_text_alter_example_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['id'], 'verbose_name': 'Cсылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
