# Generated by Django 4.0.8 on 2022-12-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_alter_links_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='name_title',
            new_name='name',
        ),
    ]
